[[redirects]]
  from = "https://musikversicherung.netlify.app/*"
  to = "https://musikversicherung.com/:splat"
  status = 301
[[redirects]]
  from = "https://musikversicherung.com/wp-content/uploads/2015/05/Tipps-zu-Auslandsreisen.pdf"
  to = "https://musikversicherung.com/Empfehlungen-zu-Auslandsreisen.pdf"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 